export enum CodeError {
  USER_ALREADY_EXISTS= 'USER_ALREADY_EXISTS',
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  UNSECURE_PASSWORD =  'UNSECURE_PASSWORD',
  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
  INVALID_EMAIL = 'INVALID_EMAIL',
  USERNAME_TAKEN = 'USERNAME_TAKEN',
  INTERNAL_ERROR = 'INTERNAL_ERROR'
}
