### Register
POST http://localhost:1234/auth/register
Content-Type: application/json

{
  "username": "araldev",
  "password": "123456",
  "email": "araldev@gmail.com"
}

### Login
POST http://localhost:1234/auth/login
Content-Type: application/json

{
  "username": "Berto",
  "password": "123456"
}

### Logout
POST http://localhost:1234/auth/logout
Content-Type: application/json